### PR TITLE
Run CI against Windows

### PR DESCRIPTION
**Pull request by Mogztter**
Brace for impact :laughing:

### CODE REVIEW

**Comment by anb0s** [comment]
Looks better now :) will rebase and try localy when merged.

Should fix #68 then.

**Comment by anb0s** [comment]
rebased to `upstream/ci-windows` (this PR) and all tests passed @ windows :)

**Comment by Mogztter** [comment]
Awesome!
You're ready to go :rocket:

**Comment by anb0s** [comment]
Thank You for all the support 👍

**Pull request merged**
