### PR TITLE
use shx for all unix (bash, sh) commands

### LINKED ISSUE #226: [dev] npm run clean and nmp run dist not working @ Windows (cmd)
npm run clean:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asciidoctor-kroki@0.12.0 clean: `rm -rf dist/*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the asciidoctor-kroki@0.12.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### PR DESCRIPTION
**Pull request by anb0s**
fixes #226

### CODE REVIEW

**Comment by anb0s** [comment]
@Mogztter  It looks like the `package-lock.json` produced in my environment (Node 14.x LTS) uses `"lockfileVersion"=1`, but checked in version has laready `"lockfileVersion"=2` i think created with Node 15.x and NPM 7.x ?

**Comment by anb0s** [comment]
Should we use latest Node or LTS (like documented in README.md) for development?

**Comment by Mogztter** [comment]
Apparently, Node 14.15.5 includes npm 6 (not npm 7):

> Latest LTS Version: 14.15.5 (includes npm 6.14.11)


I'm pretty sure nvm/npm asked me to upgrade npm using: `npm i -g npm`, that's why I'm now using:

```console
$ npm -v
7.5.4
```

```console
$ node -v
v14.15.4
```

I thought that `package-lock.json` files generated by npm 7 were backward compatible with npm 6:

> One change to take note of is the new lockfile format, which is backwards compatible with npm 6 users. The lockfile v2 unlocks the ability to do deterministic and reproducible builds to produce a package tree.

https://github.blog/2021-02-02-npm-7-is-now-generally-available/#breaking-changes

> Should we use latest Node or LTS (like documented in README.md) for development?

Yes, Node 12 is now in "Maintenance LTS" mode so we can build against Node 14 LTS and Node 15 current.

**Comment by anb0s** [comment]
I've this versions at Windows:
```
>node -v
v14.15.5
>npm -v
6.14.11
```
this is why the format 1 is generated localy and there are lot of changes to the checked in version :)

I've tried to update to npm 7.x, but there is an issue at windows and `npm i -g npm` does not work :(

To fix build failure in this PR i will update to latest node and npm...

**Comment by anb0s** [comment]
OK, i've found how-to update to NPM v7.x @ windows and updated the README.md :)

**Comment by anb0s** [comment]
@Mogztter Thank You for review :) and doc fixes 👍

**Pull request merged**
