### PR TITLE
Ruby: fix spelling of wavedrom

### PR DESCRIPTION
**Pull request by ahus1**
This problem seems to be introduced by commit 3dfc3154f8017fdc4eaba17c33052859dce6e852

### CODE REVIEW

**Comment by Mogztter** [comment]
Good catch, thanks :+1: 

I inverted the M into a W... yikes!
Could you please add "wavedrom" in here: https://github.com/Mogztter/asciidoctor-kroki/blob/35f75e232a5671fe4e404a9b6e4516e011b5919e/ruby/spec/asciidoctor_kroki_spec.rb#L83

Hopefully it will prevent another regression :sweat_smile:

**Comment by ahus1** [comment]
Thanks for updating the test, have been in meetings all day...

**Comment by Mogztter** [comment]
No worries, and thank _you_ for fixing bugs :wink: 
I will try to cut a release in the new few days.

**Comment by ahus1** [comment]
No need to rush for a release (at least not for me). The IntelliJ plugin still uses copy-and-paste for this dependency. I opened two more PRs; they forward some downstream changes upstream. Again, no rush here.

**Pull request merged**
